/// Macro to implement the string ergonomics for a generated constrained-string newtype.
///
/// Generates:
/// - `AsRef<str>` borrowing the inner `String`
/// - `PartialEq<str>`, `PartialEq<&str>`, and `PartialEq<String>`, in both operand orders
///
/// Invocations of this macro are generated by the type-generator for every single-field
/// `String` tuple struct in the `schema/*/schema.rs` and `schema/*/testcases_schema.rs` files.
macro_rules! impl_string_newtype_ergonomics {
    ($ident:ident) => {
        impl ::std::convert::AsRef<str> for $ident {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }

        impl ::std::cmp::PartialEq<str> for $ident {
            fn eq(&self, other: &str) -> bool {
                self.0 == other
            }
        }

        impl ::std::cmp::PartialEq<&str> for $ident {
            fn eq(&self, other: &&str) -> bool {
                self.0 == *other
            }
        }

        impl ::std::cmp::PartialEq<::std::string::String> for $ident {
            fn eq(&self, other: &::std::string::String) -> bool {
                self.0 == *other
            }
        }

        impl ::std::cmp::PartialEq<$ident> for str {
            fn eq(&self, other: &$ident) -> bool {
                *self == other.0
            }
        }

        impl ::std::cmp::PartialEq<$ident> for &str {
            fn eq(&self, other: &$ident) -> bool {
                **self == other.0
            }
        }

        impl ::std::cmp::PartialEq<$ident> for ::std::string::String {
            fn eq(&self, other: &$ident) -> bool {
                *self == other.0
            }
        }
    };
}

pub(crate) use impl_string_newtype_ergonomics;
