#![allow(dead_code)]
#![allow(clippy::all)]
#![cfg_attr(any(), rustfmt::skip)]
/*!
 * This file is automatically generated by type-generator.
 * Do not edit manually!
 * Re-generate with: cargo run --locked -p type-generator
 */
use regex::Regex;
use std::collections::HashMap;
use std::sync::LazyLock;
/// Lookup array of `(system_name, text_pattern)`
static REGISTRY_ENTRIES: &[(&str, &str)] = &[
    ("https://euvd.enisa.europa.eu", "^EUVD-[1-9][0-9]{3}-[0-9]{4,}$"),
    ("https://github.com/oasis-tcs/csaf", "^#[1-9]\\d*$"),
];
/// Lazy regex cache
static REGEX_CACHE: LazyLock<HashMap<&'static str, Regex>> = LazyLock::new(|| {
    REGISTRY_ENTRIES
        .iter()
        .map(|&(sn, pattern)| {
            let re = Regex::new(pattern)
                .expect(
                    "The pattern should be parseable as a regex. This is validated during type generation. Please re-run type generation. (This looks like a dev error)",
                );
            (sn, re)
        })
        .collect()
});
/// Looks up a rvisc entry by `system_name`
/// Returns `(system_name, text_pattern)` if found
pub fn lookup(system_name: &str) -> Option<(&'static str, &'static str)> {
    REGISTRY_ENTRIES
        .binary_search_by(|&(sn, _)| sn.cmp(system_name))
        .ok()
        .map(|idx| REGISTRY_ENTRIES[idx])
}
/// Looks up a rvisc entry by `system_name` and returns its pattern as a compiled `Regex`.
pub fn lookup_regex(system_name: &str) -> Option<&'static Regex> {
    REGEX_CACHE.get(system_name)
}
/// Checks if the given `system_name` is a known rvisc entry
pub fn is_registered_id_system(system_name: &str) -> bool {
    lookup(system_name).is_some()
}
