name: Defect Report
description: Create a report to help us improve
title: "[Defect]: "
type: bug
body:
  - type: markdown
    attributes:
      value: |
        **Describe the defect**
        A clear and concise description of what the defect is.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a clear set of steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      multiple: true
      description: Please select your operating system.
      options:
        - Windows
        - macOS
        - Linux
        - Other

  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      description: Please select your system architecture.
      options:
        - x86_64 (Intel/AMD 64-bit)
        - aarch64 (ARM 64-bit)
        - wasm32 (WebAssembly)
        - Other


  - type: input
    id: lib-version
    attributes:
      label: Version of the crate
      placeholder: 0.32.0
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust version
      placeholder: 1.88.0
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
