/*!
 * This file is automatically generated by type-generator.
 * Do not edit manually!
 * Re-generate with: cargo run --locked -p type-generator
 */
#![allow(clippy::all)]
#![cfg_attr(any(), rustfmt::skip)]
#![allow(rustdoc::all)]
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///Contains the URL of the JSON schema for test result which the document promises to be valid for.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "JSON schema",
///  "description": "Contains the URL of the JSON schema for test result which the document promises to be valid for.",
///  "type": "string",
///  "format": "uri",
///  "enum": [
///    "https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.1/test/validator/testresult_json_schema.json"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum JsonSchema {
    #[serde(
        rename = "https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.1/test/validator/testresult_json_schema.json"
    )]
    HttpsRawGithubusercontentComOasisTcsCsafMasterCsaf21TestValidatorTestresultJsonSchemaJson,
}
impl ::std::fmt::Display for JsonSchema {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::HttpsRawGithubusercontentComOasisTcsCsafMasterCsaf21TestValidatorTestresultJsonSchemaJson => {
                f.write_str(
                    "https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.1/test/validator/testresult_json_schema.json",
                )
            }
        }
    }
}
impl ::std::str::FromStr for JsonSchema {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.1/test/validator/testresult_json_schema.json" => {
                Ok(
                    Self::HttpsRawGithubusercontentComOasisTcsCsafMasterCsaf21TestValidatorTestresultJsonSchemaJson,
                )
            }
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for JsonSchema {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for JsonSchema {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for JsonSchema {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Contains the message detailing what the issues is.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "Message",
///  "description": "Contains the message detailing what the issues is.",
///  "type": "string",
///  "minLength": 1
///}
/// ```
/// </details>
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct Message(::std::string::String);
impl ::std::ops::Deref for Message {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<Message> for ::std::string::String {
    fn from(value: Message) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for Message {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for Message {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Message {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Message {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for Message {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///Contains the section number of the test in the specification.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "Number of the test",
///  "description": "Contains the section number of the test in the specification.",
///  "type": "string",
///  "pattern": "^6\\.(([1-3]\\.[1-9])|(1\\.10)|([12]\\.1[1-9])|(3\\.1[0-8])|(3\\.19\\.[1-5])|([12]\\.2[0-6])|(2\\.27)|([12]\\.2[8-9])|(1\\.27\\.([1-9]|1[0-9]))|(3\\.2[02])|(3\\.21\\.[1-9])|([12]\\.3[0-8])|(1\\.39)|(2\\.39\\.[1-5])|([12]\\.4[0-9])|(1\\.5[0-9])|(2\\.50\\.[1-3])|(2\\.5[1-3])|(2\\.54\\.[1-4])|(1\\.60\\.[1-3])|(1\\.6[1]))$"
///}
/// ```
/// </details>
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct NumberOfTheTest(::std::string::String);
impl ::std::ops::Deref for NumberOfTheTest {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<NumberOfTheTest> for ::std::string::String {
    fn from(value: NumberOfTheTest) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for NumberOfTheTest {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        {
            ::regress::Regex::new(
                    "^6\\.(([1-3]\\.[1-9])|(1\\.10)|([12]\\.1[1-9])|(3\\.1[0-8])|(3\\.19\\.[1-5])|([12]\\.2[0-6])|(2\\.27)|([12]\\.2[8-9])|(1\\.27\\.([1-9]|1[0-9]))|(3\\.2[02])|(3\\.21\\.[1-9])|([12]\\.3[0-8])|(1\\.39)|(2\\.39\\.[1-5])|([12]\\.4[0-9])|(1\\.5[0-9])|(2\\.50\\.[1-3])|(2\\.5[1-3])|(2\\.54\\.[1-4])|(1\\.60\\.[1-3])|(1\\.6[1]))$",
                )
                .unwrap()
        });
        if PATTERN.find(value).is_none() {
            return Err(
                "doesn't match pattern \"^6\\.(([1-3]\\.[1-9])|(1\\.10)|([12]\\.1[1-9])|(3\\.1[0-8])|(3\\.19\\.[1-5])|([12]\\.2[0-6])|(2\\.27)|([12]\\.2[8-9])|(1\\.27\\.([1-9]|1[0-9]))|(3\\.2[02])|(3\\.21\\.[1-9])|([12]\\.3[0-8])|(1\\.39)|(2\\.39\\.[1-5])|([12]\\.4[0-9])|(1\\.5[0-9])|(2\\.50\\.[1-3])|(2\\.5[1-3])|(2\\.54\\.[1-4])|(1\\.60\\.[1-3])|(1\\.6[1]))$\""
                    .into(),
            );
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for NumberOfTheTest {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for NumberOfTheTest {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for NumberOfTheTest {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for NumberOfTheTest {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///Contains the result for a given test.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "Result",
///  "description": "Contains the result for a given test.",
///  "type": "object",
///  "required": [
///    "id",
///    "passed"
///  ],
///  "properties": {
///    "errors": {
///      "title": "Errors",
///      "description": "Contains a list of errors.",
///      "$ref": "#/$defs/validation_messages_t"
///    },
///    "id": {
///      "title": "Number of the test",
///      "description": "Contains the section number of the test in the specification.",
///      "type": "string",
///      "pattern": "^6\\.(([1-3]\\.[1-9])|(1\\.10)|([12]\\.1[1-9])|(3\\.1[0-8])|(3\\.19\\.[1-5])|([12]\\.2[0-6])|(2\\.27)|([12]\\.2[8-9])|(1\\.27\\.([1-9]|1[0-9]))|(3\\.2[02])|(3\\.21\\.[1-9])|([12]\\.3[0-8])|(1\\.39)|(2\\.39\\.[1-5])|([12]\\.4[0-9])|(1\\.5[0-9])|(2\\.50\\.[1-3])|(2\\.5[1-3])|(2\\.54\\.[1-4])|(1\\.60\\.[1-3])|(1\\.6[1]))$"
///    },
///    "infos": {
///      "title": "Information",
///      "description": "Contains a list of information.",
///      "$ref": "#/$defs/validation_messages_t"
///    },
///    "passed": {
///      "title": "Passed",
///      "description": "States whether the data passed this specific test.",
///      "type": "boolean"
///    },
///    "warnings": {
///      "title": "Warnings",
///      "description": "Contains a list of warnings.",
///      "$ref": "#/$defs/validation_messages_t"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ResultT {
    ///Contains a list of errors.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub errors: ::std::option::Option<ValidationMessagesT>,
    ///Contains the section number of the test in the specification.
    pub id: NumberOfTheTest,
    ///Contains a list of information.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub infos: ::std::option::Option<ValidationMessagesT>,
    ///States whether the data passed this specific test.
    pub passed: bool,
    ///Contains a list of warnings.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub warnings: ::std::option::Option<ValidationMessagesT>,
}
impl ResultT {
    pub fn builder() -> builder::ResultT {
        Default::default()
    }
}
///Representation of the expected result for a given test file from the test suite provided for section 6 of the specification.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "$id": "https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.1/test/validator/testresult_json_schema.json",
///  "title": "Test result for a single CSAF test file",
///  "description": "Representation of the expected result for a given test file from the test suite provided for section 6 of the specification.",
///  "type": "object",
///  "required": [
///    "$schema",
///    "overall_valid",
///    "primary_result",
///    "resultschema_version"
///  ],
///  "properties": {
///    "$schema": {
///      "title": "JSON schema",
///      "description": "Contains the URL of the JSON schema for test result which the document promises to be valid for.",
///      "type": "string",
///      "format": "uri",
///      "enum": [
///        "https://raw.githubusercontent.com/oasis-tcs/csaf/master/csaf_2.1/test/validator/testresult_json_schema.json"
///      ]
///    },
///    "overall_valid": {
///      "title": "Overall valid",
///      "description": "States whether the file passes all basic tests. This might differ from the result for the specific test.",
///      "type": "boolean"
///    },
///    "primary_result": {
///      "title": "Primary result",
///      "description": "Contains the expected result for this specific test. Results for any other tests may be added as secondary results.",
///      "$ref": "#/$defs/result_t"
///    },
///    "resultschema_version": {
///      "title": "Result version",
///      "description": "Contains the current version of this schema",
///      "type": "string",
///      "const": "2.1"
///    },
///    "secondary_results": {
///      "title": "Secondary results",
///      "description": "Contains a list of expected result for other tests. It is not guaranteed to contain expected results for all other tests. Main purpose is to aid in understanding edge cases.",
///      "items": {
///        "$ref": "#/$defs/result_t"
///      },
///      "minItems": 1,
///      "uniqueItems": true
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct TestResultForASingleCsafTestFile {
    ///States whether the file passes all basic tests. This might differ from the result for the specific test.
    pub overall_valid: bool,
    ///Contains the expected result for this specific test. Results for any other tests may be added as secondary results.
    pub primary_result: ResultT,
    ///Contains the current version of this schema
    pub resultschema_version: ::std::string::String,
    ///Contains the URL of the JSON schema for test result which the document promises to be valid for.
    #[serde(rename = "$schema")]
    pub schema: JsonSchema,
    ///Contains a list of expected result for other tests. It is not guaranteed to contain expected results for all other tests. Main purpose is to aid in understanding edge cases.
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub secondary_results: ::std::option::Option<Vec<ResultT>>,
}
impl TestResultForASingleCsafTestFile {
    pub fn builder() -> builder::TestResultForASingleCsafTestFile {
        Default::default()
    }
}
///Contains a message and the instance path it occurred.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "Validation message",
///  "description": "Contains a message and the instance path it occurred.",
///  "type": "object",
///  "required": [
///    "instance_path",
///    "message"
///  ],
///  "properties": {
///    "instance_path": {
///      "title": "Instance path",
///      "description": "Contains a JSON pointer detailing the path to the instance that raised the issue.",
///      "type": "string",
///      "format": "json-pointer",
///      "pattern": "^(/([^~\\/]|(~[01]))*)+$"
///    },
///    "message": {
///      "title": "Message",
///      "description": "Contains the message detailing what the issues is.",
///      "type": "string",
///      "minLength": 1
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ValidationMessageT {
    ///Contains a JSON pointer detailing the path to the instance that raised the issue.
    pub instance_path: ::std::string::String,
    ///Contains the message detailing what the issues is.
    pub message: Message,
}
impl ValidationMessageT {
    pub fn builder() -> builder::ValidationMessageT {
        Default::default()
    }
}
///Contains a list of validation messages.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "Validation messages",
///  "description": "Contains a list of validation messages.",
///  "items": {
///    "$ref": "#/$defs/validation_message_t"
///  },
///  "minItems": 1,
///  "uniqueItems": true
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
#[serde(transparent)]
pub struct ValidationMessagesT(pub Vec<ValidationMessageT>);
impl ::std::ops::Deref for ValidationMessagesT {
    type Target = Vec<ValidationMessageT>;
    fn deref(&self) -> &Vec<ValidationMessageT> {
        &self.0
    }
}
impl ::std::convert::From<ValidationMessagesT> for Vec<ValidationMessageT> {
    fn from(value: ValidationMessagesT) -> Self {
        value.0
    }
}
impl ::std::convert::From<Vec<ValidationMessageT>> for ValidationMessagesT {
    fn from(value: Vec<ValidationMessageT>) -> Self {
        Self(value)
    }
}
/// Types for composing complex structures.
pub mod builder {
    #[derive(Clone, Debug)]
    pub struct ResultT {
        errors: ::std::result::Result<
            ::std::option::Option<super::ValidationMessagesT>,
            ::std::string::String,
        >,
        id: ::std::result::Result<super::NumberOfTheTest, ::std::string::String>,
        infos: ::std::result::Result<
            ::std::option::Option<super::ValidationMessagesT>,
            ::std::string::String,
        >,
        passed: ::std::result::Result<bool, ::std::string::String>,
        warnings: ::std::result::Result<
            ::std::option::Option<super::ValidationMessagesT>,
            ::std::string::String,
        >,
    }
    impl ::std::default::Default for ResultT {
        fn default() -> Self {
            Self {
                errors: Ok(Default::default()),
                id: Err("no value supplied for id".to_string()),
                infos: Ok(Default::default()),
                passed: Err("no value supplied for passed".to_string()),
                warnings: Ok(Default::default()),
            }
        }
    }
    impl ResultT {
        pub fn errors<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<
                ::std::option::Option<super::ValidationMessagesT>,
            >,
            T::Error: ::std::fmt::Display,
        {
            self.errors = value
                .try_into()
                .map_err(|e| format!("error converting supplied value for errors: {e}"));
            self
        }
        pub fn id<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<super::NumberOfTheTest>,
            T::Error: ::std::fmt::Display,
        {
            self.id = value
                .try_into()
                .map_err(|e| format!("error converting supplied value for id: {e}"));
            self
        }
        pub fn infos<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<
                ::std::option::Option<super::ValidationMessagesT>,
            >,
            T::Error: ::std::fmt::Display,
        {
            self.infos = value
                .try_into()
                .map_err(|e| format!("error converting supplied value for infos: {e}"));
            self
        }
        pub fn passed<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<bool>,
            T::Error: ::std::fmt::Display,
        {
            self.passed = value
                .try_into()
                .map_err(|e| format!("error converting supplied value for passed: {e}"));
            self
        }
        pub fn warnings<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<
                ::std::option::Option<super::ValidationMessagesT>,
            >,
            T::Error: ::std::fmt::Display,
        {
            self.warnings = value
                .try_into()
                .map_err(|e| {
                    format!("error converting supplied value for warnings: {e}")
                });
            self
        }
    }
    impl ::std::convert::TryFrom<ResultT> for super::ResultT {
        type Error = super::error::ConversionError;
        fn try_from(
            value: ResultT,
        ) -> ::std::result::Result<Self, super::error::ConversionError> {
            Ok(Self {
                errors: value.errors?,
                id: value.id?,
                infos: value.infos?,
                passed: value.passed?,
                warnings: value.warnings?,
            })
        }
    }
    impl ::std::convert::From<super::ResultT> for ResultT {
        fn from(value: super::ResultT) -> Self {
            Self {
                errors: Ok(value.errors),
                id: Ok(value.id),
                infos: Ok(value.infos),
                passed: Ok(value.passed),
                warnings: Ok(value.warnings),
            }
        }
    }
    #[derive(Clone, Debug)]
    pub struct TestResultForASingleCsafTestFile {
        overall_valid: ::std::result::Result<bool, ::std::string::String>,
        primary_result: ::std::result::Result<super::ResultT, ::std::string::String>,
        resultschema_version: ::std::result::Result<
            ::std::string::String,
            ::std::string::String,
        >,
        schema: ::std::result::Result<super::JsonSchema, ::std::string::String>,
        secondary_results: ::std::result::Result<
            ::std::option::Option<Vec<super::ResultT>>,
            ::std::string::String,
        >,
    }
    impl ::std::default::Default for TestResultForASingleCsafTestFile {
        fn default() -> Self {
            Self {
                overall_valid: Err("no value supplied for overall_valid".to_string()),
                primary_result: Err("no value supplied for primary_result".to_string()),
                resultschema_version: Err(
                    "no value supplied for resultschema_version".to_string(),
                ),
                schema: Err("no value supplied for schema".to_string()),
                secondary_results: Ok(Default::default()),
            }
        }
    }
    impl TestResultForASingleCsafTestFile {
        pub fn overall_valid<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<bool>,
            T::Error: ::std::fmt::Display,
        {
            self.overall_valid = value
                .try_into()
                .map_err(|e| {
                    format!("error converting supplied value for overall_valid: {e}")
                });
            self
        }
        pub fn primary_result<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<super::ResultT>,
            T::Error: ::std::fmt::Display,
        {
            self.primary_result = value
                .try_into()
                .map_err(|e| {
                    format!("error converting supplied value for primary_result: {e}")
                });
            self
        }
        pub fn resultschema_version<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<::std::string::String>,
            T::Error: ::std::fmt::Display,
        {
            self.resultschema_version = value
                .try_into()
                .map_err(|e| {
                    format!(
                        "error converting supplied value for resultschema_version: {e}"
                    )
                });
            self
        }
        pub fn schema<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<super::JsonSchema>,
            T::Error: ::std::fmt::Display,
        {
            self.schema = value
                .try_into()
                .map_err(|e| format!("error converting supplied value for schema: {e}"));
            self
        }
        pub fn secondary_results<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<::std::option::Option<Vec<super::ResultT>>>,
            T::Error: ::std::fmt::Display,
        {
            self.secondary_results = value
                .try_into()
                .map_err(|e| {
                    format!("error converting supplied value for secondary_results: {e}")
                });
            self
        }
    }
    impl ::std::convert::TryFrom<TestResultForASingleCsafTestFile>
    for super::TestResultForASingleCsafTestFile {
        type Error = super::error::ConversionError;
        fn try_from(
            value: TestResultForASingleCsafTestFile,
        ) -> ::std::result::Result<Self, super::error::ConversionError> {
            Ok(Self {
                overall_valid: value.overall_valid?,
                primary_result: value.primary_result?,
                resultschema_version: value.resultschema_version?,
                schema: value.schema?,
                secondary_results: value.secondary_results?,
            })
        }
    }
    impl ::std::convert::From<super::TestResultForASingleCsafTestFile>
    for TestResultForASingleCsafTestFile {
        fn from(value: super::TestResultForASingleCsafTestFile) -> Self {
            Self {
                overall_valid: Ok(value.overall_valid),
                primary_result: Ok(value.primary_result),
                resultschema_version: Ok(value.resultschema_version),
                schema: Ok(value.schema),
                secondary_results: Ok(value.secondary_results),
            }
        }
    }
    #[derive(Clone, Debug)]
    pub struct ValidationMessageT {
        instance_path: ::std::result::Result<
            ::std::string::String,
            ::std::string::String,
        >,
        message: ::std::result::Result<super::Message, ::std::string::String>,
    }
    impl ::std::default::Default for ValidationMessageT {
        fn default() -> Self {
            Self {
                instance_path: Err("no value supplied for instance_path".to_string()),
                message: Err("no value supplied for message".to_string()),
            }
        }
    }
    impl ValidationMessageT {
        pub fn instance_path<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<::std::string::String>,
            T::Error: ::std::fmt::Display,
        {
            self.instance_path = value
                .try_into()
                .map_err(|e| {
                    format!("error converting supplied value for instance_path: {e}")
                });
            self
        }
        pub fn message<T>(mut self, value: T) -> Self
        where
            T: ::std::convert::TryInto<super::Message>,
            T::Error: ::std::fmt::Display,
        {
            self.message = value
                .try_into()
                .map_err(|e| {
                    format!("error converting supplied value for message: {e}")
                });
            self
        }
    }
    impl ::std::convert::TryFrom<ValidationMessageT> for super::ValidationMessageT {
        type Error = super::error::ConversionError;
        fn try_from(
            value: ValidationMessageT,
        ) -> ::std::result::Result<Self, super::error::ConversionError> {
            Ok(Self {
                instance_path: value.instance_path?,
                message: value.message?,
            })
        }
    }
    impl ::std::convert::From<super::ValidationMessageT> for ValidationMessageT {
        fn from(value: super::ValidationMessageT) -> Self {
            Self {
                instance_path: Ok(value.instance_path),
                message: Ok(value.message),
            }
        }
    }
}
