// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./csaf_ffi.wasm', import.meta.url), 'csaf_ffi');

export type CsafErrorVariant =
  | { tag: 'InvalidJson', message: string }
  | { tag: 'MissingVersion', message: string }
  | { tag: 'UnsupportedVersion', version: string }
  | { tag: 'LoadError', message: string };

export class CsafError extends Error {
  override readonly name = 'CsafError' as const;
  constructor(public readonly variant: CsafErrorVariant) {
    const { tag, ...fields } = variant;
    const fmt = (v: unknown) => typeof v === 'object' && v !== null ? JSON.stringify(v) : String(v);
    const msg = Object.entries(fields).map(([k, v]) => `${k}=${fmt(v)}`).join(', ');
    super(msg ? `${tag}: ${msg}` : tag, { cause: variant });
  }
  static InvalidJson(message: string): CsafError { return new CsafError({ tag: 'InvalidJson', message }); }
  static MissingVersion(message: string): CsafError { return new CsafError({ tag: 'MissingVersion', message }); }
  static UnsupportedVersion(version: string): CsafError { return new CsafError({ tag: 'UnsupportedVersion', version }); }
  static LoadError(message: string): CsafError { return new CsafError({ tag: 'LoadError', message }); }
}

/** Result of a single validation test. */
export interface TestResult {
  testId: string;
  status: TestResultStatus;
}

/**
 * A single validation error with a message and the JSON path where it occurred.
 */
export interface ValidationError {
  message: string;
  instancePath: string;
}

/** Overall result of a CSAF validation run. */
export interface ValidationResult {
  /** Whether the validation was successful (no errors). */
  success: boolean;
  /** The detected CSAF version. */
  version: string;
  /** Individual test results. */
  testResults: TestResult[];
  /** Total number of errors. */
  numErrors: bigint;
  /** Total number of warnings. */
  numWarnings: bigint;
  /** Total number of informational findings. */
  numInfos: bigint;
  /** Total number of tests not found. */
  numNotFound: bigint;
}

export interface Cwe {
  id: string;
  name: string;
  version: string | null;
}

export interface ProductReference {
  productId: string;
  jsonPath: string;
}

/** Status of a single test execution. */
export type TestResultStatus =
  | { tag: 'Success' }
  | { tag: 'Failure', errors: ValidationError[], warnings: ValidationError[], infos: ValidationError[] }
  | { tag: 'NotFound' }
  | { tag: 'Skipped' };

export type CsafDateTime =
  | { tag: 'Valid', rawString: string, utcString: string }
  | { tag: 'Invalid', rawString: string };

export type CsafLanguage =
  | { tag: 'Valid', value: string }
  | { tag: 'Invalid', value: string };

export type CsafVersion = 'V20' | 'V21';

export type DocumentCategory =
  | { tag: 'CsafBase' }
  | { tag: 'CsafInformationalAdvisory' }
  | { tag: 'CsafSecurityIncidentResponse' }
  | { tag: 'CsafSecurityAdvisory' }
  | { tag: 'CsafVex' }
  | { tag: 'CsafWithdrawn' }
  | { tag: 'CsafSuperseded' }
  | { tag: 'CsafDeprecatedSecurityAdvisory' }
  | { tag: 'CsafBaseOther', value: string };

export type ProductStatusGroup = 'Affected' | 'NotAffected' | 'Fixed' | 'UnderInvestigation' | 'Unknown' | 'Recommended';

/**
 * A parsed CSAF document (2.0 or 2.1).
 *
 * Create via [`CsafDocument::from_json`] (auto-detect) or
 * [`CsafDocument::from_json_2_0`] / [`CsafDocument::from_json_2_1`].
 */
export class CsafDocument {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('CsafDocument object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_csaf_ffi_fn_free_csafdocument', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): CsafDocument { return new CsafDocument(handle); }
  /**
   * Parse a CSAF document from JSON, auto-detecting the version.
   * @throws {CsafError}
   */
  static fromJson(jsonStr: string): CsafDocument {
    const _rb_jsonStr = _rt.lowerString(jsonStr);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_jsonStr);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_constructor_csafdocument_from_json', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.readHandleElement(_retPtr);
      return new CsafDocument(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Parse a CSAF 2.0 document from JSON.
   * @throws {CsafError}
   */
  static fromJson20(jsonStr: string): CsafDocument {
    const _rb_jsonStr = _rt.lowerString(jsonStr);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_jsonStr);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_constructor_csafdocument_from_json_2_0', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.readHandleElement(_retPtr);
      return new CsafDocument(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Parse a CSAF 2.1 document from JSON.
   * @throws {CsafError}
   */
  static fromJson21(jsonStr: string): CsafDocument {
    const _rb_jsonStr = _rt.lowerString(jsonStr);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_jsonStr);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_constructor_csafdocument_from_json_2_1', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.readHandleElement(_retPtr);
      return new CsafDocument(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /** The CSAF version of this document. */
  getVersion(): CsafVersion {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_csaf_ffi_fn_clone_csafdocument', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_method_csafdocument_get_version', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftCsafVersion(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** The version string ("2.0" or "2.1"). */
  getVersionString(): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_csaf_ffi_fn_clone_csafdocument', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_method_csafdocument_get_version_string', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Run a single validation test by ID.
   * @throws {CsafError}
   */
  runTest(testId: string): TestResult {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_csaf_ffi_fn_clone_csafdocument', this._handle);
    const _rb_testId = _rt.lowerString(testId);
    const _argPtr = _rt.scratchAlloc(4 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeRustBufferElements(_argPtr + 8, _rb_testId);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_method_csafdocument_run_test', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftTestResult(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Run specific validation tests by their IDs.
   * @throws {CsafError}
   */
  runTests(testIds: string[]): ValidationResult {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_csaf_ffi_fn_clone_csafdocument', this._handle);
    const _rb_testIds = _rt.lowerIntoBuffer((w) => { w.writeSequence(testIds, (_w, _v) => { _w.writeString(_v); }); });
    const _argPtr = _rt.scratchAlloc(4 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeRustBufferElements(_argPtr + 8, _rb_testIds);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_method_csafdocument_run_tests', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftValidationResult(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** The original JSON string used to create this document. */
  toJson(): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_csaf_ffi_fn_clone_csafdocument', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_method_csafdocument_to_json', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Run validation with the given preset ("basic", "extended", "full").
   * @throws {CsafError}
   */
  validate(preset: string): ValidationResult {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_csaf_ffi_fn_clone_csafdocument', this._handle);
    const _rb_preset = _rt.lowerString(preset);
    const _argPtr = _rt.scratchAlloc(4 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeRustBufferElements(_argPtr + 8, _rb_preset);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_method_csafdocument_validate', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftValidationResult(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_csaf_ffi_fn_free_csafdocument', this._handle);
  }
}
if (Symbol.dispose) (CsafDocument as any).prototype[Symbol.dispose] = CsafDocument.prototype.free;

// --- Serialization helpers ---

function _lowerTestResult(w: UniFFIWriter, value: TestResult): void {
  w.writeString(value.testId);
  _lowerTestResultStatus(w, value.status);
}
function _liftTestResult(r: UniFFIReader): TestResult {
  return {
    testId: r.readString(),
    status: _liftTestResultStatus(r),
  };
}

function _lowerValidationError(w: UniFFIWriter, value: ValidationError): void {
  w.writeString(value.message);
  w.writeString(value.instancePath);
}
function _liftValidationError(r: UniFFIReader): ValidationError {
  return {
    message: r.readString(),
    instancePath: r.readString(),
  };
}

function _lowerValidationResult(w: UniFFIWriter, value: ValidationResult): void {
  w.writeBool(value.success);
  w.writeString(value.version);
  w.writeSequence(value.testResults, (_w, _v) => { _lowerTestResult(_w, _v); });
  w.writeU64(value.numErrors);
  w.writeU64(value.numWarnings);
  w.writeU64(value.numInfos);
  w.writeU64(value.numNotFound);
}
function _liftValidationResult(r: UniFFIReader): ValidationResult {
  return {
    success: r.readBool(),
    version: r.readString(),
    testResults: r.readSequence((_r) => _liftTestResult(_r)),
    numErrors: r.readU64(),
    numWarnings: r.readU64(),
    numInfos: r.readU64(),
    numNotFound: r.readU64(),
  };
}

function _lowerCwe(w: UniFFIWriter, value: Cwe): void {
  w.writeString(value.id);
  w.writeString(value.name);
  w.writeOptional(value.version, (_w, _v) => { _w.writeString(_v); });
}
function _liftCwe(r: UniFFIReader): Cwe {
  return {
    id: r.readString(),
    name: r.readString(),
    version: r.readOptional((_r) => _r.readString()),
  };
}

function _lowerProductReference(w: UniFFIWriter, value: ProductReference): void {
  w.writeString(value.productId);
  w.writeString(value.jsonPath);
}
function _liftProductReference(r: UniFFIReader): ProductReference {
  return {
    productId: r.readString(),
    jsonPath: r.readString(),
  };
}

function _lowerTestResultStatus(w: UniFFIWriter, value: TestResultStatus): void {
  if (value.tag === 'Success') {
    w.writeI32(1);
    return;
  }
  if (value.tag === 'Failure') {
    w.writeI32(2);
    w.writeSequence(value.errors, (_w, _v) => { _lowerValidationError(_w, _v); });
    w.writeSequence(value.warnings, (_w, _v) => { _lowerValidationError(_w, _v); });
    w.writeSequence(value.infos, (_w, _v) => { _lowerValidationError(_w, _v); });
    return;
  }
  if (value.tag === 'NotFound') {
    w.writeI32(3);
    return;
  }
  if (value.tag === 'Skipped') {
    w.writeI32(4);
    return;
  }
  throw new Error(`Unknown TestResultStatus variant: ${(value as any).tag}`);
}
function _liftTestResultStatus(r: UniFFIReader): TestResultStatus {
  const ordinal = r.readI32();
  if (ordinal === 1) {
    return { tag: 'Success' };
  }
  if (ordinal === 2) {
    return { tag: 'Failure', errors: r.readSequence((_r) => _liftValidationError(_r)), warnings: r.readSequence((_r) => _liftValidationError(_r)), infos: r.readSequence((_r) => _liftValidationError(_r)) };
  }
  if (ordinal === 3) {
    return { tag: 'NotFound' };
  }
  if (ordinal === 4) {
    return { tag: 'Skipped' };
  }
  throw new Error(`Unknown TestResultStatus ordinal: ${ordinal}`);
}

function _lowerCsafDateTime(w: UniFFIWriter, value: CsafDateTime): void {
  if (value.tag === 'Valid') {
    w.writeI32(1);
    w.writeString(value.rawString);
    w.writeString(value.utcString);
    return;
  }
  if (value.tag === 'Invalid') {
    w.writeI32(2);
    w.writeString(value.rawString);
    return;
  }
  throw new Error(`Unknown CsafDateTime variant: ${(value as any).tag}`);
}
function _liftCsafDateTime(r: UniFFIReader): CsafDateTime {
  const ordinal = r.readI32();
  if (ordinal === 1) {
    return { tag: 'Valid', rawString: r.readString(), utcString: r.readString() };
  }
  if (ordinal === 2) {
    return { tag: 'Invalid', rawString: r.readString() };
  }
  throw new Error(`Unknown CsafDateTime ordinal: ${ordinal}`);
}

function _lowerCsafLanguage(w: UniFFIWriter, value: CsafLanguage): void {
  if (value.tag === 'Valid') {
    w.writeI32(1);
    w.writeString(value.value);
    return;
  }
  if (value.tag === 'Invalid') {
    w.writeI32(2);
    w.writeString(value.value);
    return;
  }
  throw new Error(`Unknown CsafLanguage variant: ${(value as any).tag}`);
}
function _liftCsafLanguage(r: UniFFIReader): CsafLanguage {
  const ordinal = r.readI32();
  if (ordinal === 1) {
    return { tag: 'Valid', value: r.readString() };
  }
  if (ordinal === 2) {
    return { tag: 'Invalid', value: r.readString() };
  }
  throw new Error(`Unknown CsafLanguage ordinal: ${ordinal}`);
}

function _lowerCsafVersion(w: UniFFIWriter, value: CsafVersion): void {
  if (value === 'V20') { w.writeI32(1); return; }
  if (value === 'V21') { w.writeI32(2); return; }
  throw new Error(`Unknown CsafVersion variant: ${value}`);
}
function _liftCsafVersion(r: UniFFIReader): CsafVersion {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'V20';
  if (ordinal === 2) return 'V21';
  throw new Error(`Unknown CsafVersion ordinal: ${ordinal}`);
}

function _lowerDocumentCategory(w: UniFFIWriter, value: DocumentCategory): void {
  if (value.tag === 'CsafBase') {
    w.writeI32(1);
    return;
  }
  if (value.tag === 'CsafInformationalAdvisory') {
    w.writeI32(2);
    return;
  }
  if (value.tag === 'CsafSecurityIncidentResponse') {
    w.writeI32(3);
    return;
  }
  if (value.tag === 'CsafSecurityAdvisory') {
    w.writeI32(4);
    return;
  }
  if (value.tag === 'CsafVex') {
    w.writeI32(5);
    return;
  }
  if (value.tag === 'CsafWithdrawn') {
    w.writeI32(6);
    return;
  }
  if (value.tag === 'CsafSuperseded') {
    w.writeI32(7);
    return;
  }
  if (value.tag === 'CsafDeprecatedSecurityAdvisory') {
    w.writeI32(8);
    return;
  }
  if (value.tag === 'CsafBaseOther') {
    w.writeI32(9);
    w.writeString(value.value);
    return;
  }
  throw new Error(`Unknown DocumentCategory variant: ${(value as any).tag}`);
}
function _liftDocumentCategory(r: UniFFIReader): DocumentCategory {
  const ordinal = r.readI32();
  if (ordinal === 1) {
    return { tag: 'CsafBase' };
  }
  if (ordinal === 2) {
    return { tag: 'CsafInformationalAdvisory' };
  }
  if (ordinal === 3) {
    return { tag: 'CsafSecurityIncidentResponse' };
  }
  if (ordinal === 4) {
    return { tag: 'CsafSecurityAdvisory' };
  }
  if (ordinal === 5) {
    return { tag: 'CsafVex' };
  }
  if (ordinal === 6) {
    return { tag: 'CsafWithdrawn' };
  }
  if (ordinal === 7) {
    return { tag: 'CsafSuperseded' };
  }
  if (ordinal === 8) {
    return { tag: 'CsafDeprecatedSecurityAdvisory' };
  }
  if (ordinal === 9) {
    return { tag: 'CsafBaseOther', value: r.readString() };
  }
  throw new Error(`Unknown DocumentCategory ordinal: ${ordinal}`);
}

function _lowerProductStatusGroup(w: UniFFIWriter, value: ProductStatusGroup): void {
  if (value === 'Affected') { w.writeI32(1); return; }
  if (value === 'NotAffected') { w.writeI32(2); return; }
  if (value === 'Fixed') { w.writeI32(3); return; }
  if (value === 'UnderInvestigation') { w.writeI32(4); return; }
  if (value === 'Unknown') { w.writeI32(5); return; }
  if (value === 'Recommended') { w.writeI32(6); return; }
  throw new Error(`Unknown ProductStatusGroup variant: ${value}`);
}
function _liftProductStatusGroup(r: UniFFIReader): ProductStatusGroup {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'Affected';
  if (ordinal === 2) return 'NotAffected';
  if (ordinal === 3) return 'Fixed';
  if (ordinal === 4) return 'UnderInvestigation';
  if (ordinal === 5) return 'Unknown';
  if (ordinal === 6) return 'Recommended';
  throw new Error(`Unknown ProductStatusGroup ordinal: ${ordinal}`);
}

function _liftErrorCsafError(rb: any): CsafError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) {
      return new CsafError({ tag: 'InvalidJson', message: r.readString() });
    }
    if (ordinal === 2) {
      return new CsafError({ tag: 'MissingVersion', message: r.readString() });
    }
    if (ordinal === 3) {
      return new CsafError({ tag: 'UnsupportedVersion', version: r.readString() });
    }
    if (ordinal === 4) {
      return new CsafError({ tag: 'LoadError', message: r.readString() });
    }
    throw new Error(`Unknown CsafError ordinal: ${ordinal}`);
  });
}

export namespace CsafFfi {
  /**
   * Validate a CSAF document from a JSON string.
   *
   * Auto-detects the CSAF version from the document's `document.csaf_version`
   * field and validates it according to the specified preset.
   *
   * # Arguments
   *
   * * `json_str` - The CSAF document as a JSON string.
   * * `preset`   - The validation preset: `"basic"`, `"extended"`, or `"full"`.
   *
   * # Returns
   *
   * An `ValidationResult` containing the validation outcome and any findings.
   * @throws {CsafError}
   */
  export function validateCsaf(jsonStr: string, preset: string): ValidationResult {
    const _rb_jsonStr = _rt.lowerString(jsonStr);
    const _rb_preset = _rt.lowerString(preset);
    const _argPtr = _rt.scratchAlloc(6 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_jsonStr);
    _rt.writeRustBufferElements(_argPtr + 24, _rb_preset);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_func_validate_csaf', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftValidationResult(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Validate a CSAF 2.0 document from a JSON string.
   *
   * # Arguments
   *
   * * `json_str` - The CSAF 2.0 document as a JSON string.
   * * `preset`   - The validation preset: `"basic"`, `"extended"`, or `"full"`.
   * @throws {CsafError}
   */
  export function validateCsaf20(jsonStr: string, preset: string): ValidationResult {
    const _rb_jsonStr = _rt.lowerString(jsonStr);
    const _rb_preset = _rt.lowerString(preset);
    const _argPtr = _rt.scratchAlloc(6 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_jsonStr);
    _rt.writeRustBufferElements(_argPtr + 24, _rb_preset);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_func_validate_csaf_2_0', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftValidationResult(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Validate a CSAF 2.1 document from a JSON string.
   *
   * # Arguments
   *
   * * `json_str` - The CSAF 2.1 document as a JSON string.
   * * `preset`   - The validation preset: `"basic"`, `"extended"`, or `"full"`.
   * @throws {CsafError}
   */
  export function validateCsaf21(jsonStr: string, preset: string): ValidationResult {
    const _rb_jsonStr = _rt.lowerString(jsonStr);
    const _rb_preset = _rt.lowerString(preset);
    const _argPtr = _rt.scratchAlloc(6 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_jsonStr);
    _rt.writeRustBufferElements(_argPtr + 24, _rb_preset);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_csaf_ffi_fn_func_validate_csaf_2_1', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorCsafError(rb));
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftValidationResult(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
