#![allow(clippy::all)]
#![cfg_attr(any(), rustfmt::skip)]
/*!
 * This file is automatically generated by build.rs.
 * Do not edit manually!
 */
crate::macros::define_csaf_test!(
    Test6_1_1, ValidatorForTest6_1_1, id : "6.1.1", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-01-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-01-s01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-01-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_2, ValidatorForTest6_1_2, id : "6.1.2", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-02-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-02-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-02-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-02-s01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_3, ValidatorForTest6_1_3, id : "6.1.3", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-03-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-03-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-03-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-03-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-03-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-03-s02.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_4, ValidatorForTest6_1_4, id : "6.1.4", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-04-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-04-s01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-04-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_5, ValidatorForTest6_1_5, id : "6.1.5", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-05-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-05-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-05-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-05-s01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-05-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-05-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_6, ValidatorForTest6_1_6, id : "6.1.6", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-04.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-05.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-05.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-14.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-14.json"), (case_15, "15",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-15.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-06-15.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_7, ValidatorForTest6_1_7, id : "6.1.7", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-07-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-07-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-07-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-07-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-07-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-07-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_8, ValidatorForTest6_1_8, id : "6.1.8", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-03.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-14.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-08-14.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_9, ValidatorForTest6_1_9, id : "6.1.9", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-03.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-09-13.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_10, ValidatorForTest6_1_10, id : "6.1.10", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-10-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-10-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_11, ValidatorForTest6_1_11, id : "6.1.11", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-11-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-11-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_12, ValidatorForTest6_1_12, id : "6.1.12", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-12-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-12-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s02.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s12.json"), (case_s13, "s13",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s13.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-12-s13.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_13, ValidatorForTest6_1_13, id : "6.1.13", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-13-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-13-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s03.json"), (case_s04, "s04",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s04.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s04.json"), (case_s05, "s05",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s05.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-13-s05.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_14, ValidatorForTest6_1_14, id : "6.1.14", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-04.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-05.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-06.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-06.json"), (case_07, "07",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-07.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-07.json"), (case_08, "08",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-08.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-08.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-14.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-14.json"), (case_15, "15",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-15.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-15.json"), (case_16, "16",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-16.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-16.json"), (case_17, "17",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-17.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-17.json"), (case_18, "18",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-18.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-18.json"), (case_19, "19",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-19.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-14-19.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_15, ValidatorForTest6_1_15, id : "6.1.15", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-15-12.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-15-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-15-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_16, ValidatorForTest6_1_16, id : "6.1.16", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-04.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-05.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-06.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-06.json"), (case_07, "07",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-07.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-07.json"), (case_08, "08",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-08.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-08.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-14.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-14.json"), (case_15, "15",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-15.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-15.json"), (case_16, "16",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-16.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-16.json"), (case_17, "17",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-17.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-17.json"), (case_18, "18",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-18.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-18.json"), (case_19, "19",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-19.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-19.json"), (case_31, "31",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-31.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-16-31.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_17, ValidatorForTest6_1_17, id : "6.1.17", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-17-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-17-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s03.json"), (case_s04, "s04",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s04.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s04.json"), (case_s05, "s05",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s05.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s05.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s12.json"), (case_s13, "s13",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s13.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s13.json"), (case_s14, "s14",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s14.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-17-s14.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_18, ValidatorForTest6_1_18, id : "6.1.18", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-18-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-18-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-18-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-18-s01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-18-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-18-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_19, ValidatorForTest6_1_19, id : "6.1.19", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-19-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-19-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-19-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-19-02.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_20, ValidatorForTest6_1_20, id : "6.1.20", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-20-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-20-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-20-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-20-s01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_21, ValidatorForTest6_1_21, id : "6.1.21", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s03.json"), (case_s04, "s04",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s04.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s04.json"), (case_s05, "s05",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s05.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s05.json"), (case_s06, "s06",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s06.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s06.json"), (case_s07, "s07",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s07.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s07.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-21-13.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-21-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_22, ValidatorForTest6_1_22, id : "6.1.22", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-22-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-22-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-22-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-22-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-22-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-22-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-22-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-22-s03.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_23, ValidatorForTest6_1_23, id : "6.1.23", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-23-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-23-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s03.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-23-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_24, ValidatorForTest6_1_24, id : "6.1.24", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s03.json"), (case_s04, "s04",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s04.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s04.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-24-12.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s12.json"), (case_s13, "s13",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s13.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-24-s13.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_25, ValidatorForTest6_1_25, id : "6.1.25", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-25-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-25-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s03.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-25-s12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_26, ValidatorForTest6_1_26, id : "6.1.26", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-04.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-04.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-26-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-26-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-26-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-26-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-26-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-26-s03.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-26-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_1, ValidatorForTest6_1_27_1, id : "6.1.27.1", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-01-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-01-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_2, ValidatorForTest6_1_27_2, id : "6.1.27.2", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-02-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-02-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_3, ValidatorForTest6_1_27_3, id : "6.1.27.3", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-03-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-03-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_4, ValidatorForTest6_1_27_4, id : "6.1.27.4", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-04-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-04-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_5, ValidatorForTest6_1_27_5, id : "6.1.27.5", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-05-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-05-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-05-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-05-s01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_6, ValidatorForTest6_1_27_6, id : "6.1.27.6", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-06-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-06-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_7, ValidatorForTest6_1_27_7, id : "6.1.27.7", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-07-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-07-01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-07-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-07-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_8, ValidatorForTest6_1_27_8, id : "6.1.27.8", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-08-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-08-01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-08-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-08-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_9, ValidatorForTest6_1_27_9, id : "6.1.27.9", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-04.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-05.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-06.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-06.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-09-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-09-s01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-13.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-14.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-14.json"), (case_15, "15",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-15.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-15.json"), (case_16, "16",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-16.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-09-16.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_10, ValidatorForTest6_1_27_10, id : "6.1.27.10", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-10-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-10-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s02.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-10-s12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_27_11, ValidatorForTest6_1_27_11, id : "6.1.27.11", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-11-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-27-11-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-11-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-11-s01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-11-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-11-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-11-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-27-11-s12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_28, ValidatorForTest6_1_28, id : "6.1.28", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-28-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-28-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-28-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-28-s01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-28-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-28-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_29, ValidatorForTest6_1_29, id : "6.1.29", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-29-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-29-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-29-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-29-s01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-29-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-29-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-29-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-29-12.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-29-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-29-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-29-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-29-s12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_30, ValidatorForTest6_1_30, id : "6.1.30", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-30-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-30-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s03.json"), (case_s04, "s04",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s04.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s04.json"), (case_s05, "s05",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s05.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s05.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-30-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-30-11.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-30-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_31, ValidatorForTest6_1_31, id : "6.1.31", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-02.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-03.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-04.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-05.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-06.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-06.json"), (case_07, "07",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-07.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-07.json"), (case_08, "08",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-08.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-08.json"), (case_09, "09",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-09.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-09.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s02.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s02.json"), (case_s03, "s03",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s03.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s03.json"), (case_s04, "s04",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s04.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s04.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-12.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-31-12.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-31-s12.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_32, ValidatorForTest6_1_32, id : "6.1.32", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-32-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-32-01.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s01.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-32-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-32-11.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s11.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s11.json"), (case_s12, "s12",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s12.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s12.json"), (case_s13, "s13",
    "../type-generator/assets/tests/csaf_2.0/mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s13.json",
    "mandatory/csaf-rs_csaf-csaf_2_0-6-1-32-s13.json")]
);
crate::macros::define_csaf_test!(
    Test6_1_33, ValidatorForTest6_1_33, id : "6.1.33", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-33-01.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-33-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-33-11.json",
    "mandatory/oasis_csaf_tc-csaf_2_0-2021-6-1-33-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_1, ValidatorForTest6_2_1, id : "6.2.1", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-01-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-01-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-01-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-01-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_2, ValidatorForTest6_2_2, id : "6.2.2", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-02-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-02-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_3, ValidatorForTest6_2_3, id : "6.2.3", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-03-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-03-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_4, ValidatorForTest6_2_4, id : "6.2.4", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-04-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-04-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_5, ValidatorForTest6_2_5, id : "6.2.5", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-05-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-05-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_6, ValidatorForTest6_2_6, id : "6.2.6", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-06-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-06-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_7, ValidatorForTest6_2_7, id : "6.2.7", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-07-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-07-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_8, ValidatorForTest6_2_8, id : "6.2.8", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-08-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-08-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-08-02.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-08-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-08-s01.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-08-s01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-08-s11.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-08-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_9, ValidatorForTest6_2_9, id : "6.2.9", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-09-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-09-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-09-02.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-09-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-09-s01.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-09-s01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-09-s11.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-09-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_10, ValidatorForTest6_2_10, id : "6.2.10", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-10-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-10-01.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-10-s11.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-10-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_11, ValidatorForTest6_2_11, id : "6.2.11", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-11-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-11-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-11-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-11-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_12, ValidatorForTest6_2_12, id : "6.2.12", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-12-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-12-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_13, ValidatorForTest6_2_13, id : "6.2.13", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-13-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-13-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_14, ValidatorForTest6_2_14, id : "6.2.14", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-02.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-03.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-04.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-05.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-06.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-06.json"), (case_07, "07",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-07.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-07.json"), (case_08, "08",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-08.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-08.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-14-s01.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-14-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-14-s02.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-14-s02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-12.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-14-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_15, ValidatorForTest6_2_15, id : "6.2.15", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-15-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-15-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-15-02.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-15-02.json"), (case_s01, "s01",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-15-s01.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-15-s01.json"), (case_s02, "s02",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-15-s02.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-15-s02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-15-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-15-11.json"), (case_s11, "s11",
    "../type-generator/assets/tests/csaf_2.0/optional/csaf-rs_csaf-csaf_2_0-6-2-15-s11.json",
    "optional/csaf-rs_csaf-csaf_2_0-6-2-15-s11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_16, ValidatorForTest6_2_16, id : "6.2.16", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-16-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-16-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-16-02.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-16-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-16-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-16-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_17, ValidatorForTest6_2_17, id : "6.2.17", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-17-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-17-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-17-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-17-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_18, ValidatorForTest6_2_18, id : "6.2.18", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-18-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-18-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-18-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-18-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_19, ValidatorForTest6_2_19, id : "6.2.19", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-02.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-03.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-04.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-05.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-06.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-06.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-11.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-12.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-13.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-14.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-14.json"), (case_15, "15",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-15.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-15.json"), (case_16, "16",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-16.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-16.json"), (case_17, "17",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-17.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-19-17.json")]
);
crate::macros::define_csaf_test!(
    Test6_2_20, ValidatorForTest6_2_20, id : "6.2.20", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/optional/oasis_csaf_tc-csaf_2_0-2021-6-2-20-01.json",
    "optional/oasis_csaf_tc-csaf_2_0-2021-6-2-20-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_1, ValidatorForTest6_3_1, id : "6.3.1", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-12.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-01-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_2, ValidatorForTest6_3_2, id : "6.3.2", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-12.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-02-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_3, ValidatorForTest6_3_3, id : "6.3.3", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-12.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-03-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_4, ValidatorForTest6_3_4, id : "6.3.4", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-12.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-04-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_5, ValidatorForTest6_3_5, id : "6.3.5", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-05-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-05-01.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_6, ValidatorForTest6_3_6, id : "6.3.6", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-06-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_7, ValidatorForTest6_3_7, id : "6.3.7", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-07-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-07-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-07-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-07-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_8, ValidatorForTest6_3_8, id : "6.3.8", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-02.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-12.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-08-12.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_9, ValidatorForTest6_3_9, id : "6.3.9", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-01.json"), (case_02, "02",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-02.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-02.json"), (case_03, "03",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-03.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-03.json"), (case_04, "04",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-04.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-04.json"), (case_05, "05",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-05.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-05.json"), (case_06, "06",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-06.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-06.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-11.json"), (case_12, "12",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-12.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-12.json"), (case_13, "13",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-13.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-13.json"), (case_14, "14",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-14.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-14.json"), (case_15, "15",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-15.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-15.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_10, ValidatorForTest6_3_10, id : "6.3.10", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-10-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-10-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-10-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-10-11.json")]
);
crate::macros::define_csaf_test!(
    Test6_3_11, ValidatorForTest6_3_11, id : "6.3.11", doc_type : crate
    ::schema::csaf2_0::schema::CommonSecurityAdvisoryFramework, version : "V2_0", cases :
    [(case_01, "01",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-11-01.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-11-01.json"), (case_11, "11",
    "../csaf/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-11-11.json",
    "informative/oasis_csaf_tc-csaf_2_0-2021-6-3-11-11.json")]
);
crate::macros::define_test_cases_aggregate!(
    const_name : TESTS_2_0, mandatory : [(test_6_1_1, Test6_1_1, ValidatorForTest6_1_1),
    (test_6_1_2, Test6_1_2, ValidatorForTest6_1_2), (test_6_1_3, Test6_1_3,
    ValidatorForTest6_1_3), (test_6_1_4, Test6_1_4, ValidatorForTest6_1_4), (test_6_1_5,
    Test6_1_5, ValidatorForTest6_1_5), (test_6_1_6, Test6_1_6, ValidatorForTest6_1_6),
    (test_6_1_7, Test6_1_7, ValidatorForTest6_1_7), (test_6_1_8, Test6_1_8,
    ValidatorForTest6_1_8), (test_6_1_9, Test6_1_9, ValidatorForTest6_1_9), (test_6_1_10,
    Test6_1_10, ValidatorForTest6_1_10), (test_6_1_11, Test6_1_11,
    ValidatorForTest6_1_11), (test_6_1_12, Test6_1_12, ValidatorForTest6_1_12),
    (test_6_1_13, Test6_1_13, ValidatorForTest6_1_13), (test_6_1_14, Test6_1_14,
    ValidatorForTest6_1_14), (test_6_1_15, Test6_1_15, ValidatorForTest6_1_15),
    (test_6_1_16, Test6_1_16, ValidatorForTest6_1_16), (test_6_1_17, Test6_1_17,
    ValidatorForTest6_1_17), (test_6_1_18, Test6_1_18, ValidatorForTest6_1_18),
    (test_6_1_19, Test6_1_19, ValidatorForTest6_1_19), (test_6_1_20, Test6_1_20,
    ValidatorForTest6_1_20), (test_6_1_21, Test6_1_21, ValidatorForTest6_1_21),
    (test_6_1_22, Test6_1_22, ValidatorForTest6_1_22), (test_6_1_23, Test6_1_23,
    ValidatorForTest6_1_23), (test_6_1_24, Test6_1_24, ValidatorForTest6_1_24),
    (test_6_1_25, Test6_1_25, ValidatorForTest6_1_25), (test_6_1_26, Test6_1_26,
    ValidatorForTest6_1_26), (test_6_1_27_1, Test6_1_27_1, ValidatorForTest6_1_27_1),
    (test_6_1_27_2, Test6_1_27_2, ValidatorForTest6_1_27_2), (test_6_1_27_3,
    Test6_1_27_3, ValidatorForTest6_1_27_3), (test_6_1_27_4, Test6_1_27_4,
    ValidatorForTest6_1_27_4), (test_6_1_27_5, Test6_1_27_5, ValidatorForTest6_1_27_5),
    (test_6_1_27_6, Test6_1_27_6, ValidatorForTest6_1_27_6), (test_6_1_27_7,
    Test6_1_27_7, ValidatorForTest6_1_27_7), (test_6_1_27_8, Test6_1_27_8,
    ValidatorForTest6_1_27_8), (test_6_1_27_9, Test6_1_27_9, ValidatorForTest6_1_27_9),
    (test_6_1_27_10, Test6_1_27_10, ValidatorForTest6_1_27_10), (test_6_1_27_11,
    Test6_1_27_11, ValidatorForTest6_1_27_11), (test_6_1_28, Test6_1_28,
    ValidatorForTest6_1_28), (test_6_1_29, Test6_1_29, ValidatorForTest6_1_29),
    (test_6_1_30, Test6_1_30, ValidatorForTest6_1_30), (test_6_1_31, Test6_1_31,
    ValidatorForTest6_1_31), (test_6_1_32, Test6_1_32, ValidatorForTest6_1_32),
    (test_6_1_33, Test6_1_33, ValidatorForTest6_1_33)], recommended : [(test_6_2_1,
    Test6_2_1, ValidatorForTest6_2_1), (test_6_2_2, Test6_2_2, ValidatorForTest6_2_2),
    (test_6_2_3, Test6_2_3, ValidatorForTest6_2_3), (test_6_2_4, Test6_2_4,
    ValidatorForTest6_2_4), (test_6_2_5, Test6_2_5, ValidatorForTest6_2_5), (test_6_2_6,
    Test6_2_6, ValidatorForTest6_2_6), (test_6_2_7, Test6_2_7, ValidatorForTest6_2_7),
    (test_6_2_8, Test6_2_8, ValidatorForTest6_2_8), (test_6_2_9, Test6_2_9,
    ValidatorForTest6_2_9), (test_6_2_10, Test6_2_10, ValidatorForTest6_2_10),
    (test_6_2_11, Test6_2_11, ValidatorForTest6_2_11), (test_6_2_12, Test6_2_12,
    ValidatorForTest6_2_12), (test_6_2_13, Test6_2_13, ValidatorForTest6_2_13),
    (test_6_2_14, Test6_2_14, ValidatorForTest6_2_14), (test_6_2_15, Test6_2_15,
    ValidatorForTest6_2_15), (test_6_2_16, Test6_2_16, ValidatorForTest6_2_16),
    (test_6_2_17, Test6_2_17, ValidatorForTest6_2_17), (test_6_2_18, Test6_2_18,
    ValidatorForTest6_2_18), (test_6_2_19, Test6_2_19, ValidatorForTest6_2_19),
    (test_6_2_20, Test6_2_20, ValidatorForTest6_2_20)], informative : [(test_6_3_1,
    Test6_3_1, ValidatorForTest6_3_1), (test_6_3_2, Test6_3_2, ValidatorForTest6_3_2),
    (test_6_3_3, Test6_3_3, ValidatorForTest6_3_3), (test_6_3_4, Test6_3_4,
    ValidatorForTest6_3_4), (test_6_3_5, Test6_3_5, ValidatorForTest6_3_5), (test_6_3_6,
    Test6_3_6, ValidatorForTest6_3_6), (test_6_3_7, Test6_3_7, ValidatorForTest6_3_7),
    (test_6_3_8, Test6_3_8, ValidatorForTest6_3_8), (test_6_3_9, Test6_3_9,
    ValidatorForTest6_3_9), (test_6_3_10, Test6_3_10, ValidatorForTest6_3_10),
    (test_6_3_11, Test6_3_11, ValidatorForTest6_3_11)]
);
