#![allow(dead_code)]
#![allow(clippy::all)]
#![cfg_attr(any(), rustfmt::skip)]
/*!
 * This file is automatically generated by type-generator.
 * Do not edit manually!
 * Re-generate with: cargo run --locked -p type-generator
 */
/// Lookup array of `(system_name, text_pattern)`
pub(super) static REGISTRY_ENTRIES: &[(&str, &str)] = &[
    ("https://euvd.enisa.europa.eu", "^EUVD-[1-9][0-9]{3}-[0-9]{4,}$"),
    ("https://github.com/oasis-tcs/csaf", "^#[1-9]\\d*$"),
];
