#![allow(dead_code)]
#![allow(clippy::all)]
#![cfg_attr(any(), rustfmt::skip)]
/*!
 * This file is automatically generated by type-generator.
 * Do not edit manually!
 * Re-generate with: cargo run --locked -p type-generator
 */
pub static LICENSE_TRANSLATIONS: &[(&str, &str)] = &[("de", "Lizenz")];
pub static PRODUCT_DESCRIPTION_TRANSLATIONS: &[(&str, &str)] = &[
    ("de", "Produktbeschreibung"),
];
pub static REASONING_FOR_SUPERSESSION_TRANSLATIONS: &[(&str, &str)] = &[
    ("de", "Begründung für die Ersetzung"),
];
pub static REASONING_FOR_WITHDRAWAL_TRANSLATIONS: &[(&str, &str)] = &[
    ("de", "Begründung für die Zurückziehung"),
];
pub static SUPERSEDING_DOCUMENT_TRANSLATIONS: &[(&str, &str)] = &[
    ("de", "Ersetzendes Dokument"),
];
